using CSL.API;

namespace StandardRecordTest
{
    public record Standard(site[] site) : APIRecord;
    public record site(regions[] regions, categories categories, catgraph catgraph, people people, open_auctions open_auctions, closed_auctions closed_auctions) : APIRecord;
    public record regions(africa africa, asia asia, australia australia, europe europe, namerica namerica, samerica samerica) : APIRecord;
    public record africa(africaitem[] item) : APIRecord;
    public record africaitem([Attribute] string id, string location, bool quantity, string name, string payment, itemdescription[] description, string shipping, incategory incategory, mailbox mailbox) : APIRecord;
    public record itemdescription(descriptionparlist parlist, descriptiontext[] text) : APIRecord;
    public record descriptionparlist(listitem[] listitem) : APIRecord;
    public record listitem(listitemtext text, listitemparlist parlist) : APIRecord;
    public record listitemtext(keyword keyword) : APIRecord;
    public record keyword(string bold) : APIRecord;
    public record incategory([Attribute] string category) : APIRecord;
    public record mailbox(mail[] mail) : APIRecord;
    public record mail(string from, string to, DateTime date, mailtext[] text) : APIRecord;
    public record mailtext(keyword keyword, emph emph, string bold) : APIRecord;
    public record emph(string bold) : APIRecord;
    public record asia(asiaitem[] item) : APIRecord;
    public record asiaitem([Attribute] string id, string location, bool quantity, string name, string payment, itemdescription[] description, string shipping, incategory incategory, mailbox mailbox) : APIRecord;
    public record descriptiontext(emph emph, string bold, keyword keyword) : APIRecord;
    public record australia(australiaitem[] item) : APIRecord;
    public record australiaitem([Attribute] string id, string location, bool quantity, string name, string payment, itemdescription[] description, string shipping, incategory incategory, mailbox mailbox) : APIRecord;
    public record europe(europeitem[] item) : APIRecord;
    public record europeitem([Attribute] string id, string location, bool quantity, string name, string payment, itemdescription[] description, string shipping, incategory incategory, mailbox mailbox) : APIRecord;
    public record namerica(namericaitem[] item) : APIRecord;
    public record namericaitem([Attribute] string id, string location, bool quantity, string name, string payment, itemdescription[] description, string shipping, incategory incategory, mailbox mailbox) : APIRecord;
    public record listitemparlist(listitem[] listitem) : APIRecord;
    public record samerica(samericaitem[] item) : APIRecord;
    public record samericaitem([Attribute] string id, string location, bool quantity, string name, string payment, itemdescription[] description, string shipping, incategory incategory, mailbox mailbox) : APIRecord;
    public record categories(category[] category) : APIRecord;
    public record category([Attribute] string id, string name, categorydescription description) : APIRecord;
    public record categorydescription(descriptiontext[] text) : APIRecord;
    public record catgraph(edge[] edge) : APIRecord;
    public record edge([Attribute] string from, [Attribute] string to) : APIRecord;
    public record people(person[] person) : APIRecord;
    public record person([Attribute] string id, string name, string emailaddress, string phone, string homepage, string creditcard, profile[] profile, watches watches) : APIRecord;
    public record profile([Attribute] float income, interest interest, string education, bool business) : APIRecord;
    public record interest([Attribute] string category) : APIRecord;
    public record watches(watch watch) : APIRecord;
    public record watch([Attribute] byte[] open_auction) : APIRecord;
    public record open_auctions(open_auction[] open_auction) : APIRecord;
    public record open_auction([Attribute] string id, float initial, float reserve, bidder[] bidder, float current, open_auctionitemref itemref, open_auctionseller seller, open_auctionannotation[] annotation, bool quantity, string type, interval[] interval) : APIRecord;
    public record bidder(DateTime date, TimeSpan time, personref personref, float increase) : APIRecord;
    public record personref([Attribute] string person) : APIRecord;
    public record open_auctionitemref([Attribute] string item) : APIRecord;
    public record open_auctionseller([Attribute] string person) : APIRecord;
    public record open_auctionannotation(author author, annotationdescription description, byte happiness) : APIRecord;
    public record author([Attribute] string person) : APIRecord;
    public record annotationdescription(descriptiontext[] text) : APIRecord;
    public record interval(DateTime start, DateTime end) : APIRecord;
    public record closed_auctions(closed_auction[] closed_auction) : APIRecord;
    public record closed_auction(closed_auctionseller seller, buyer buyer, closed_auctionitemref itemref, float price, DateTime date, bool quantity, byte[] type, closed_auctionannotation[] annotation) : APIRecord;
    public record closed_auctionseller([Attribute] string person) : APIRecord;
    public record buyer([Attribute] string person) : APIRecord;
    public record closed_auctionitemref([Attribute] string item) : APIRecord;
    public record closed_auctionannotation(author author, annotationdescription description, byte happiness) : APIRecord;
}